version: '3.8'

services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    image: uracilo/flask-mysql:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/tasks_db"
    ports:
      - "5000:5000"
    restart: always

volumes:
  db_data: {}