name: Build and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-mysql-test:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-mysql-test:latest

      - name: Pull Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-mysql-test:latest
      
      - name: Stop and remove all  Docker Containers
        run: |
          docker-compose -f test.yml build 

      - name: Stop and remove all  Docker Containers
        run: |
          docker-compose -f test.yml down 

      - name: Run Docker Container
        run: |
          docker-compose -f test.yml --env-file .env  up -d
